# https://markus.oberlehner.net/blog/running-nuxt-3-in-a-docker-container/
version: "3"

# volumes:
#   node_modules:

services:
  nuxt-app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - HOST=0.0.0.0
