services:
  directus:
    image: "directus/directus:11.1.0"
    volumes:
      - "directus-uploads:/directus/uploads"
      - "directus-extensions:/directus/extensions"
    environment:
      - SERVICE_FQDN_DIRECTUS_8055
      - KEY=$SERVICE_BASE64_64_KEY
      - SECRET=$SERVICE_BASE64_64_SECRET
      - "ADMIN_EMAIL=${ADMIN_EMAIL}"
      - ADMIN_PASSWORD=$SERVICE_PASSWORD_ADMIN
      - DB_CLIENT=postgres
      - DB_HOST=postgresql
      - DB_PORT=5432
      - "DB_DATABASE=${POSTGRESQL_DATABASE:-directus}"
      - DB_USER=$SERVICE_USER_POSTGRESQL
      - DB_PASSWORD=$SERVICE_PASSWORD_POSTGRESQL
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - WEBSOCKETS_ENABLED=true
      - CORS_ENABLED=true
      - CORS_ORIGIN=http://localhost:3000,https://vie-publique-git-develop-dakticsn.vercel.app,https://test.vie-publique.sn,https://www.vie-publique.sn,https://vie-publique-pwa.vercel.app,https://cartografree.vercel.app,https://www.cartografree.sn
      - CORS_METHODS=GET
      - STORAGE_S3_DRIVER=s3
      - STORAGE_S3_KEY=$SERVICE_MINIO_ROOT_USER
      - STORAGE_S3_SECRET=$SERVICE_MINIO_ROOT_PASSWORD
      - STORAGE_S3_BUCKET=directus-bucket
      - STORAGE_S3_REGION=us-east-1
      - STORAGE_S3_ENDPOINT=http://minio:9000
      - STORAGE_S3_ROOT=directus
      - STORAGE_S3_ACL=public-read
      - STORAGE_LOCATIONS=s3,local
      - STORAGE_S3_FORCE_PATH_STYLE=true
    healthcheck:
      test:
        - CMD
        - wget
        - "-q"
        - "--spider"
        - "http://127.0.0.1:8055/admin/login"
      interval: 5s
      timeout: 20s
      retries: 10
    depends_on:
      postgresql:
        condition: service_healthy
      redis:
        condition: service_healthy
  postgresql:
    image: "postgis/postgis:16-3.4-alpine"
    volumes:
      - "directus-postgresql-data:/var/lib/postgresql/data"
    environment:
      - "POSTGRES_USER=${SERVICE_USER_POSTGRESQL}"
      - "POSTGRES_PASSWORD=${SERVICE_PASSWORD_POSTGRESQL}"
      - "POSTGRES_DB=${POSTGRESQL_DATABASE:-directus}"
    healthcheck:
      test:
        - CMD-SHELL
        - "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"
      interval: 5s
      timeout: 20s
      retries: 10
  redis:
    image: "redis:7-alpine"
    command: "redis-server --appendonly yes"
    volumes:
      - "directus-redis-data:/data"
    healthcheck:
      test:
        - CMD
        - redis-cli
        - ping
      interval: 5s
      timeout: 20s
      retries: 10
  minio:
    user: root
    image: bitnami/minio:2023.8.29-debian-11-r0
    environment:
      BITNAMI_DEBUG: "true"
      MINIO_ROOT_USER: $SERVICE_MINIO_ROOT_USER
      MINIO_ROOT_PASSWORD: $SERVICE_MINIO_ROOT_PASSWORD
    ports:
      - "9000:9000" # Port API S3
      - "9001:9001" # Port Console Web
    volumes:
      - "/var/lib/minio/data:/bitnami/minio/data"
