export const useSiteMetadata = () => {
  const config = useRuntimeConfig();
  const siteUrl = config.public.siteUrl || "https://www.vie-publique.sn";

  return {
    siteName: "Vie Publique Sénégal",
    siteUrl,
    defaultTitle:
      "Vie Publique Sénégal - Information citoyenne et actualité politique",
    defaultDescription:
      "Suivez l'actualité politique, les débats publics et la vie démocratique au Sénégal. Informations officielles, analyses et décryptages pour une citoyenneté éclairée.",
    defaultImage: `${siteUrl}/images/logo-vie-publique.webp`,
    defaultLocale: "fr_SN",
    twitterHandle: "@viepubliquesn",
    twitterCardType: "summary_large_image",
    themeColor: "#1E40AF",
    keywords: [
      "actualité politique Sénégal",
      "vie publique Sénégal",
      "information citoyenne Sénégal",
      "démocratie sénégalaise",
      "politique sénégalaise",
      "débats publics Sénégal",
      "institutions sénégalaises",
      "gouvernement Sénégal",
      "assemblée nationale Sénégal",
      "élections Sénégal",
      "citoyenneté sénégalaise",
      "service public Sénégal",
      "Macky Sall",
      "Bassirou Diomaye Faye",
      "président Sénégal",
      "ministres Sénégal",
      "conseil des ministres",
      "parlement sénégalais",
      "décrets présidentiels",
      "lois sénégalaises",
      "réformes Sénégal",
      "justice sénégalaise",
      "conseil constitutionnel Sénégal",
      "collectivités locales Sénégal",
      "maires Sénégal",
      "conseils départementaux",
      "HCCT Sénégal",
      "CESE Sénégal",
      "transparence gouvernementale",
      "bonne gouvernance Sénégal",
      "corruption Sénégal",
      "Ofnac",
      "Cour des comptes Sénégal",
      "budget État Sénégal",
      "finances publiques Sénégal",
      "plan Sénégal émergent",
      "PSE 2035",
      "développement Sénégal",
      "politiques publiques",
      "santé publique Sénégal",
      "éducation Sénégal",
      "économie sénégalaise",
      "agriculture Sénégal",
      "pêche Sénégal",
      "tourisme Sénégal",
      "infrastructure Sénégal",
      "énergie Sénégal",
      "diplomatie sénégalaise",
      "CEDEAO",
      "Union africaine",
      "coopération internationale",
      "Dakar capitale",
      "régions Sénégal",
      "Thiès",
      "Saint-Louis",
      "Kaolack",
      "Ziguinchor",
      "Tambacounda",
      "Kaffrine",
      "Kédougou",
      "Kolda",
      "Matam",
      "Louga",
      "Fatick",
      "Sédhiou",
      "société civile Sénégal",
      "ONG Sénégal",
      "syndicats Sénégal",
      "médias Sénégal",
      "liberté de presse",
      "droits de l'homme Sénégal",
    ],
  };
};